image:
  file: .gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: docker-up
    init: sudo docker-up
  - name: ddev
    prebuild: |
      sudo docker-up &
      export DDEV_NONINTERACTIVE=true
      chmod 777 .ddev/gitpod-setup-ddev.sh
      ./.ddev/gitpod-setup-ddev.sh
      ddev composer install
      ddev exec touch public/FIRST_INSTALL
    init: |
      chmod 777 .ddev/gitpod-setup-ddev.sh
      ./.ddev/gitpod-setup-ddev.sh
      ddev composer install
      ddev exec touch public/FIRST_INSTALL
      gp await-port 8080 && gp preview $(gp url 8080)
      echo "TYPO3: "$(gp url 8080)
      echo "PhpMyAdmin: "$(gp url 8036)
      echo "MailHog: "$(gp url 8025)
# Set the following ports public
ports:
  - port: 6942
    onOpen: ignore
  - port: 8080
  - port: 8025
    onOpen: ignore
  - port: 8026
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  - port: 8037
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 8043
    onOpen: ignore
  - port: 36255
    onOpen: ignore
  - port: 9999

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

vscode:
  extensions:
    - pkief.material-icon-theme
    - coenraads.bracket-pair-colorizer-2
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - editorconfig.editorconfig
    - mrmlnc.vscode-scss

